#include <stdio.h>
#include <iostream>
using namespace std;



int main()
{
	int t,n;
	printf("Type t \n");
	scanf("%d",&t);
	for (int i = 0; i < t; ++i)
	{
    cout << "type n \n";
	scanf("%d",&n);
	for (int i = 0; i < n; ++i)
		{
			int a[i][i+1];
			cin << 
			// for(int j=0; j<=i;j++)
			// {
   //          cout << "TYPE a[" << i << "][" << j << "]";
			// cin >> a[i][j];
   //      }
   //      for(int j=0; j<=i;j++)
			// {
			// cout << a[i][j] << "\n";
   //      }
		}
	}
	int i=0;
	while(i++ != 10000) {}
	return 0;
}
